#~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~#
#                               #
#          FunnyGuilds          #
#          4.0 Quantum          #
#                               #
#~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~#

# Wyswietlana nazwa pluginu
plugin-name: 'FunnyGuilds'

# Maksymalna dlugosc nazwy gildii
name-length: 22
# Minimalna dlugosc nazwy gildii
name-min-length: 4
# Maksymalna dlugosc tagu gildii
tag-length: 4
# Minimalna dlugosc tagu gildii
tag-min-length: 2
# Przedmioty wymagane do zalozenia gildii
items:
- 5 stone
- 5 dirt
# Przedmioty wymagane do zalozenia gildii dla osoby z uprawnieniem funnyguilds.vip
items-vip:
- 1 stone
# Odleglosc od spawnu
create-distance: 100
# Blok, jaki pojawi sie pod nami po stworzeniu gildii
create-material: ender crystal
# Na jakim poziomie ma byc wyznaczone centrum gildii
# - Wpisz 0, jezeli ma byc ustalone przez gracza
create-center-y: 60
# Czy ma tworzyc pusta przestrzen dookola centrum gildii
create-center-sphere: true
# Maxymalna ilosc czlonkow w gildii
max-members: 15

# Mozliwosc teleportacji do gildii
base-enable: true
# Czas oczekiwania na teleportacje (w sekundach)
base-delay: 5
# Koszt teleportacji do gildii (jezeli brak, wystarczy zrobic: base-items: [])
base-items:
- 1 diamond
- 1 emerald
# Koszt dolaczenia do gildii (jezeli brak, wystarczy zrobic: join-items: [])
join-items:
- 1 diamond

# Mozliwosc powiekszania gildii
enlarge-enable: true
# O ile powieksza teren gildii 1 poziom
enlarge-size: 5
# Koszt powiekszania gildii 
# - kazdy myslnik, to 1 poziom gildii
enlarge-items:
- 8 diamond
- 16 diamond
- 24 diamond
- 32 diamond
- 40 diamond
- 48 diamond
- 56 diamond
- 64 diamond
- 72 diamond
- 80 diamond

# Wielkosc regionu gildii
region-size: 50
# Minimalna odleglosc miedzy terenami gildii
region-min-distance: 10
# Czas wyswietlania powiadomienia na pasku powiadomien (w sekundach)
region-notification-time: 15
# Co ile moze byc wywolywany pasek powiadomien przez jednego gracza (w sekundach)
region-notification-cooldown: 60
# Blokowane komendy dla graczy spoza gildii na jej terenie
region-commands:
- sethome
# Przez ile sekund nie mozna budowac na terenie gildii po wybuchu
region-explode: 120

# Jaki ma byc zasieg pobieranych przedmiotow po wybuchu (jezeli chcesz wylaczyc, wpisz 0)
explode-radius: 3
# Jakie materialy i z jaka szansa maja byc niszczone po wybuchu
# <material>: <szansa (w %)
explode-materials:
  obsidian: 20
  water: 33
  lava: 33
  
# Ile zyc ma gildia
war-lives: 3
# Po jakim czasie od zalozenia mozna zaatakowac gildie
war-protection: 24h
# Ile czasu trzeba czekac do nastepnego ataku na gildie
war-wait: 24h

# Jaka waznosc ma gildia po jej zalozeniu
validity-start: 14d
# Ile czasu dodaje przedluzenie gildii
validity-time: 14d
# Ile dni przed koncem wygasania mozna przedluzyc gildie (wpisz 0, jezeli funkcja ma byc wylaczona)
validity-when: 14d
# Koszt przedluzenia gildii
validity-items:
- 10 diamond

# Ranking od ktorego rozpoczyna gracz
rank-start: 1000
# Czy trzeba kucac, zeby przy klikniecu prawym na gracza wyswietlilo informacje o nim
info-player-sneaking: true

# Czy czlonkowie gildii moga sobie zadawac obrazenia (domyslnie)
damage-guild: false
# Czy sojuszniczy moga sobie zadawac obrazenia
damage-ally: false

# Wyglad znaczika {TAG} wstawionego w format chatu
chat-guild: '&b{TAG} '
# Wyglad znaczika {RANK} wstawionego w format chatu
chat-rank: '&b{RANK} '
# Wyglad znaczika {POINTS} wstawionego w format chatu
chat-points: '&b{POINTS} '

# Symbol od ktorego zaczyna sie wiadomosc do gildii/sojusznikow/wszystkich gildii
chat-priv: '!'
chat-ally: '!!'
chat-global: '!!!'
# Wyglad wiadomosci wysylanej na czacie gildii
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-priv-design: '&8[&aChat gildii&8] &7{PLAYER}&8:&f {MESSAGE}'
# Wyglad wiadomosci wysylanej na czacie sojusznikow dla sojusznikow
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-ally-design: '&8[&6Chat sojuszniczy&8] &8{TAG} &7{PLAYER}&8:&f {MESSAGE}'
# Wyglad wiadomosci wysylanej na czacie globalnym gildii
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-global-design: '&8[&cChat globalny gildii&8] &8{TAG} &7{PLAYER}&8:&f {MESSAGE}'

# Wyglad tagu osob w gildii
prefix-our: '&a{TAG}&f '
# Wyglad tagu gildii sojuszniczej
prefix-allies: '&6{TAG}&f '
# Wyglad tagu gildii neutralnej (widziany rowniez przez graczy bez gildii)
prefix-other: '&7{TAG}&f '

# Czy wlaczyc dummy z punktami
dummy-enable: true
# Wyglad nazwy wyswietlanej (suffix, za punktami)
dummy-suffix: 'pkt'

# Wyglad listy graczy. Przedzial od 1 do 60
# Limit znakow: 30
# > Spis zmiennych:
# {ONLINE} - Liczba graczy online
# {PLAYER} - Gracz
# {PING} - Ping
# {TPS} - TPS
# {GUILD} - Gildia
# {TAG} - Tag gildii
# {POINTS} - Punkty
# {KILLS} - Zabojstwa
# {DEATHS} - Smierci
# {SECOND} - Sekunda
# {MINUTE} - Minuta
# {HOUR} - Godzina
# {PTOP-<pozycja>} - Gracz na podanym miejscu w rankingu (np. {PTOP-1}, {PTOP-60})
# {GTOP-<pozycja>} - Gildia na podanej pozycji w rankingu (np. {GTOP-1}, {PTOP-50})
player-list:
  1: '&7Nick: &b{PLAYER}'
  2: '&7Ping: &b{PING}'
  3: '&7TPS: &b{TPS}'
  
  4: '&7Punkty: &b{POINTS}'
  5: '&7Zabojstwa: &b{KILLS}'
  6: '&7Smierci: &b{DEATHS}'
  
  7: '&7Godzina: &b{HOUR}'
  8: '&7Minuta: &b{MINUTE}'
  9: '&7Sekunda: &b{SECOND}'
  
  10: '&7Online: &b{ONLINE}'
  11: '&7Gildia: &b{GUILD}'
  
  23: '&bTop 3 Gildii'
  
  25: '&71. &b{GTOP-1}'
  26: '&72. &b{GTOP-2}'
  27: '&73. &b{GTOP-3}'
  
  32: '&bTop 3 Graczy'
  
  34: '&71. &b{PTOP-1}'
  35: '&72. &b{PTOP-2}'
  36: '&73. &b{PTOP-3}'

# Tablista wlaczona
player-list-enable: false
# Co ile sekund ma odswiezac liste graczy
player-list-interval: 1
# Ping wyswietlany na tab
player-list-ping: 0
# Jezeli buguje Ci sie tablista
# - Po wejsciu gracza wszystko sie rozjezdza
# Wlacz ta opcje
player-list-patch: false
# Wyglad punktow wyswietlanych przy gildii w rankingu
player-list-points: '&7[&b{POINTS}&7]'

# Nazwy komend
commands:
  guild: 
    name: 'gildia'
    aliases:
    - 'gildie'
    - 'g'
  create:
    name: 'zaloz'
    aliases: []
  delete:
    name: 'usun'
    aliases: []
  confirm:
    name: 'potwierdz'
    aliases: []
  invite:
    name: 'zapros'
    aliases: []
  join:
    name: 'dolacz'
    aliases: []
  leave:
    name: 'opusc'
    aliases: []
  kick:
    name: 'wyrzuc'
    aliases: []
  base: 
    name: 'baza'
    aliases: []
  enlarge: 
    name: 'powieksz'
    aliases: []
  ally: 
    name: 'sojusz'
    aliases: []
  break: 
    name: 'rozwiaz'
    aliases: []
  info: 
    name: 'info'
    aliases: []
  player: 
    name: 'gracz'
    aliases: []
  top: 
    name: 'top'
    aliases:
    - 'top10'
  validity:
    name: 'przedluz'
    aliases: []
  leader:
    name: 'lider'
    aliases:
    - 'zalozyciel'
  deputy:
    name: 'zastepca'
    aliases: []
  ranking: 
    name: 'ranking'
    aliases: []

  setbase:
    name: 'ustawbaze'
    aliases:
    - 'ustawdom'
  pvp:
    name: 'pvp'
    aliases:
    - 'ustawpvp'

  # Komendy administratora
  admin:
    main: 'ga'
    add: 'ga dodaj'
    delete: 'ga usun'
    kick: 'ga wyrzuc'
    teleport: 'ga tp'
    points: 'ga points'
    kills: 'ga kills'
    deaths: 'ga deaths'
    ban: 'ga ban'
    lives: 'ga zycia'
    move: 'ga przenies'
    unban: 'ga unban'
    validity: 'ga przedluz'
    name: 'ga nazwa'

# Czy event PlayMoveEvent ma byc aktywny (odpowiada za wyswietlanie powiadomien o wejsciu na teren gildii)
event-move: true

# Co ile minut ma automatycznie zapisywac dane
data-interval: 1
# Typ zapisu danych
# Flat - Lokalne pliki
# MySQL - baza danych 
data-type:
  flat: true
  mysql: false
# Dane wymagane do polaczenia z baza
mysql:
  hostname: localhost
  port: 3306
  database: db
  user: root
  password: passwd
  
# Config Version
version: 4.0
